apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ivy

resources:
  - ../../base
  - sealed-settings.yaml

images:
  - name: registry.cn-shanghai.aliyuncs.com/ivysci/gpt-researcher
    newName: registry-vpc.cn-shanghai.aliyuncs.com/ivysci/gpt-researcher
    newTag: latest
