---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: researcher-settings
  namespace: ivy
spec:
  encryptedData:
    settings.yaml: AgCxTroQQ2fHGRneACy47yL2e1psXdFzbEasYxfgzO0TY5gzoYuNMAw3sgBxcygr0Wk2VRlCDOfgm/FR1/cgpP6j42ds0t0KWbi41W8DeZxmzwo/EoynCchP3GuE3WhUcv2xPQzwK9VbVdevNviOitzUG5u/wIcGz7kM43tL57hB2ynW/fTzApMWym8m99aEl7FNx9hIsYm1S7goYNp6TxhsYBxNYA5K0tej5IaaWyaqWMp4MlJv3mZWBSNVMPTM46rX63zkaCGme8uFf+cC8hL2Drg63Z9C3aGdWkKYESclsflbcH1MtsxsAT96nDVCytzwFFub470M56PWyfvJK3bmlEQ7Q+hk81g1SjfY96Kgb2vgkCaMInFP4qFoEjm7H4rsI2T/aTEyiFyKTxTuUNTF76PaYQdABQkZArr5hA3KJeD6bWd9iO5diNSPbWYlMwdAdm0/6E8juj23SzfLUkHgNtHXhvjNUNdvAIoZbGGYQZ0v/R8UNnzBtiNcMTzD2oEPx81J+0GWDiBkvDOaXd/X/UovYKgcM8KHwrj7NxAA/DKzYUW+xIjdW2bFKxydxWWlRz6218ZmZdnCL1vYSbeExjHqfTfcysl7FNGlKzZngLAIfYqaKGAct5fjyOhd5jDZiF24hCfYy0mKJvnz3QjnRvQnmJdZ2N3Atxsf2NdU4H5nxCO3gjzccVca7kCwTdGyLy9fECuZz7iVjdlk1e75dfh9o7HIbjSiPYSHKuq+Yr90g9JROyx+/U1xQSzdrZRQ3QK5qQIAGCO+WdE4N01scnN18Fws8/k7H/M6GgAS7BNCVAb0m9pOAEMu20p5P45GqkIGywz1bfduj+OKYor7ybaWPuLwiRkz61dwg8pKfFPYDYUsvusmo4O9pI6D7LEcCaQLKKXM/SdfZMa1jPbP88lKXt6lvSbIIPTH7accBkCYereO9AFhdQdZIxHrZTJBAaE6+zlNGNeLHzScd8AVDxjx63VECmgVN+e4V0QtJhwDBknY0Z6CNV4Ie0zrZhwNyhp93LfDJy/zOgFdkg6igL33ATV+E9j1CSAoGNo1h8ay2k6VB3Mi8OrLcJlZ4vEe6e/XlQXPWEZfZc9ZmDsmYopnf/7NTjYILVZYMN4kJ27X6FR2ZEwQGru/hLdILefMuevtrroPKvFyZUEMto/RygyzK+6VZg2jzLOcF5ixoLWbGprUFCB2yiLVQm78zCqUC/vMo/LuWmeFnRp2EcgmYX9jq9QSo5xaPnqnyd5iURbCMiPvFJ6APSduJ9LKgdVXmquLfQ==
  template:
    metadata:
      name: researcher-settings
      namespace: ivy
