apiVersion: v1
kind: Service
metadata:
  name: researcher
  labels:
    app: researcher
spec:
  selector:
    app: researcher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
